---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  yarn: true

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  #  - EMBER_TRY_SCENARIO=ember-lts-2.4
  #  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-2.10
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add phantomjs-prebuilt
#  - npm config set spin false
#  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
